base:
  build: .
  ports:
    - "3000:3000"
  container_name: osm-analytics-api
  environment:
    PORT: 3000
    NODE_PATH: app/src

cron:
  build: .
  container_name: osm-analytics-cron
  environment:
    NODE_PATH: app/src

redis:
  image: redis
  container_name: osm-analytics-redis
  ports:
    - "6379:6379"
  restart: always
