develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35729:35729"
  command: develop
  links:
    - redis
  volumes:
    - ./app/src:/opt/osm-analytics-api/app/src

redis:
  extends:
    file: base.yml
    service: redis
