version: '2'
services:
  api:
    extends:
      file: base.yml
      service: base
    command: develop
    ports:
      - 3000:3000
    environment:
      - REDIS_PORT_6379_TCP_ADDR=redis
      - REDIS_PORT_6379_TCP_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./api/app/src:/opt/osm-analytics-api/app/src
    restart: always
  cron:
    extends:
      file: base.yml
      service: cron
    command: cron
    environment:
      - REDIS_PORT_6379_TCP_ADDR=redis
      - REDIS_PORT_6379_TCP_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./api/app/src:/opt/osm-analytics-api/app/src
    restart: always
  redis:
    extends:
      file: base.yml
      service: redis
    restart: always
