develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35730:35730"
  command: develop
  links:
    - redis
  volumes:
    - ./app/src:/opt/osm-analytics-api/app/src
  restart: always
cron:
  extends:
    file: base.yml
    service: cron
  command: cron
  links:
    - redis
  volumes:
    - ./app/src:/opt/osm-analytics-api/app/src
  restart: always
redis:
  extends:
    file: base.yml
    service: redis
  restart: always
