swagger: "2.0"
info:
  description: "An API to consume OSM statistics as in the OSM Analytics client"
  version: "0.0.1"
  title: "OSM Analytics API"
  contact:
    name: "Vizzuality"
    url: "http://vizzuality.com"
  license:
    name: "MIT"
basePath: "/api/v1"
tags:
- name: "stats"
  description: "Core stats"
- name: "meta"
  description: "Metadata"
schemes:
- "http"

parameters:
  feature_type:
    name: "feature_type"
    in: "path"
    description: "A feature type (buildings, highways, etc). Use the /meta/feature-types endpoint to get a list of all available feature types. Usa 'all' to get all available features in the response."
    required: true
    type: "string"
    enum: [all, buildings, highways]

paths:

  /stats/{feature_type}/country/{iso3}:
    get:
      tags:
      - "stats"
      summary: "Gets OSM stats for a country"
      produces:
      - "application/json"
      parameters:
      - $ref: '#/parameters/feature_type'
      - name: "iso3"
        in: "path"
        description: "iso3 code of a country"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Stats"
        404:
          description: "Country not found"

  /stats/{feature_type}/area/{polygon}:
    get:
      tags:
      - "stats"
      summary: "Gets OSM stats for an arbitrary area"
      produces:
      - "application/json"
      parameters:
      - $ref: '#/parameters/feature_type'
      - name: "polygon"
        in: "path"
        description: "an area defined by a polygon encoded as a polyline (https://developers.google.com/maps/documentation/utilities/polylinealgorithm)"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Stats"
        413:
          description: "Encoded polyline is too big"

  /stats/{feature_type}/bbox/{bounds}:
    get:
      tags:
      - "stats"
      summary: "Gets OSM stats for a bounding box"
      produces:
      - "application/json"
      parameters:
      - $ref: '#/parameters/feature_type'
      - name: "bounds"
        in: "path"
        description: "Bounds expressed as {min_lng},{min_lat},{max_lng},{max_lat}"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Stats"
        405:
          description: "Invalid bounding box"

  /stats/{feature_type}/project/{project_id}:
    get:
      tags:
      - "stats"
      summary: "Gets OSM stats within the boundaries of a HOT project"
      produces:
      - "application/json"
      parameters:
      - $ref: '#/parameters/feature_type'
      - name: "project_id"
        in: "path"
        description: "id of HOT project"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Stats"
        404:
          description: "Project not found"

  /meta/countries:
    get:
      tags:
      - "meta"
      summary: "Gets all available countries"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Countries"

  /meta/country_polyline/{iso3}:
    get:
      tags:
      - "meta"
      summary: "Gets an encoded polyline for a given country ISO3 code"
      produces:
      - "application/text"
      parameters:
      - name: "iso3"
        in: "path"
        description: "iso3 code of a country"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"


  /meta/feature-types:
    get:
      tags:
      - "meta"
      summary: "Gets all available feature types (ie buildings, highways, etc)"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/FeatureType"

definitions:
  Countries:
    type: "array"
    items:
      $ref: "#/definitions/Country"
  Country:
    type: "object"
    properties:
      iso:
        type: "string"
      name:
        type: "string"

  FeatureType:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      geometry:
        type: "string"
        enum:
        - "LineString"
        - "Polygon"
      tag:
        type: "string"

  User:
    type: "object"
    description: "An OSM user"
    properties:
      osm_id:
        type: "string"
      osm_name:
        type: "string"
        description: "OSM display name. Might not be available for all users."
      feature_value:
        description: "Number of [feature type]/kms distance of [feature type] edited in this area"
        type: "integer"
        format: "int32"
      is_local:
        description: "Is the user a local or remote mapper, as a confidence value between 0 and 1 (0: very likely to be a remote mapper, 1: very likely to be a local mapper). Might not be available for all users."
        type: "integer"
        format: "int32"
  Experience:
    type: "object"
    properties:
      experience:
        type: "integer"
        format: "int32"
        description: Value between 1 - 12
      count_users:
        type: "integer"
        format: "int32"
        description: Users with this experience
  ActivityCount:
    type: "object"
    properties:
      day:
        type: "integer"
        format: "int32"
        description: Timestamp of the day
      count_features:
        type: "integer"
        format: "int32"
        description: Number of items/km of lines for this day
  ActivityUsers:
    type: "object"
    properties:
      day:
        type: "integer"
        format: "int32"
        description: Timestamp of the day
      count_users:
        type: "integer"
        format: "int32"
        description: Number of distinct users for this day

  FeatureStats:
    type: "object"
    properties:
      top_users:
        description: "A list of the users that edited features in this area"
        type: "array"
        items:
          $ref: "#/definitions/User"
      experience:
        type: "array"
        description: "User experience histogram (feature count per level of experience)"
        items:
          $ref: "#/definitions/Experience"
      activity_count:
        type: "array"
        description: "Activity histogram (feature count/length) organized by days"
        items:
          $ref: "#/definitions/ActivityCount"
      activity_users:
        type: "array"
        description: "Activity histogram (distinct users count) organized by days"
        items:
          $ref: "#/definitions/ActivityUsers"

      user_experience_min:
        type: "integer"
        format: "int32"
        description: Minimun experience for the area
      user_experience_max:
        type: "integer"
        format: "int32"
        description: Maximum experience for the area
      user_experience_mean:
        type: "integer"
        format: "float"
        description: Mean experience for the area
      count:
        type: "integer"
        format: "int32"
        description: Number of [feature type]
  Stats:
    type: "object"
    properties:
      buildings:
        $ref: "#/definitions/FeatureStats"
      highways:
        $ref: "#/definitions/FeatureStats"
